# Generated by Django 4.0 on 2022-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200, unique=True)),
                ('last_fetched', models.DateTimeField(null=True, verbose_name='last_fetched')),
            ],
        ),
        migrations.CreateModel(
            name='TweetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('raw_text', models.CharField(max_length=1000)),
                ('processed_text', models.CharField(max_length=1000)),
                ('polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sentiment', models.CharField(max_length=200)),
                ('subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('compound', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
