# Generated by Django 3.2.11 on 2022-03-23 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('ticker', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('last_fetched', models.DateTimeField(null=True, verbose_name='last_fetched')),
            ],
        ),
        migrations.CreateModel(
            name='TweetRecord',
            fields=[
                ('tweet_id', models.CharField(default='1', max_length=100, primary_key=True, serialize=False)),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('raw_text', models.TextField(blank=True, verbose_name='raw_text')),
                ('processed_text', models.TextField(blank=True, verbose_name='raw_text')),
                ('stemmed_text', models.TextField(blank=True, verbose_name='stemmed_text')),
                ('polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sentiment', models.CharField(max_length=200)),
                ('subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('retweet', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_stemmed_text', models.TextField(blank=True, verbose_name='overall_stemmed_text')),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('negative_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutraul_count', models.IntegerField(default=0)),
                ('best_tweet_positive', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('best_tweet_negative', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('best_tweet_neutral', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('best_tweet_subjectivity', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('best_tweet_polarity', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('best_tweet_compound', models.CharField(default='1489021532252823553', max_length=30, null=True)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
    ]
