# Generated by Django 4.0 on 2022-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksummary',
            name='id',
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='ticker',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
