# Generated by Django 4.0 on 2022-01-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_stocksummary_id_alter_stocksummary_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='stock',
            field=models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary'),
        ),
    ]
