# Generated by Django 4.0 on 2022-01-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tweetrecord_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='tweet_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tweetrecord',
            name='processed_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='tweetrecord',
            name='raw_text',
            field=models.CharField(max_length=10000),
        ),
    ]
