# Generated by Django 4.0 on 2022-01-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tweetrecord_tweet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweetrecord',
            name='tweet_id',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(null=True, verbose_name='date_fetched')),
                ('overall_polarity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_sentiment', models.CharField(max_length=200)),
                ('overall_subjectivity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('overall_neg', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_neu', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_pos', models.DecimalField(decimal_places=3, max_digits=20)),
                ('overall_compound', models.DecimalField(decimal_places=4, max_digits=20)),
                ('stock', models.ForeignKey(default='TSL', on_delete=django.db.models.deletion.CASCADE, to='home.stocksummary')),
            ],
        ),
    ]
