# Generated by Django 3.2.11 on 2022-01-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tweetrecord_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrecord',
            name='overall_stemmed_text',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='tweetrecord',
            name='stemmed_text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
