# Generated by Django 3.2.11 on 2022-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220123_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrecord',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='neutraul_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
    ]
