# Generated by Django 3.2.11 on 2022-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220130_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_negative',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_neutral',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_polarity',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_positive',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_subjectivity',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tweetrecord',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetrecord',
            name='retweet',
            field=models.IntegerField(default=0),
        ),
    ]
