# Generated by Django 3.2.11 on 2022-02-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220203_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrecord',
            name='best_tweet_compound',
            field=models.CharField(default='1489021532252823553', max_length=30, null=True),
        ),
    ]
